apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: pdsddi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Możesz dostosować rozmiar
  # storageClassName: "" # Odkomentuj i podaj, jeśli masz specyficzną klasę storage; inaczej użyje domyślnej