apiVersion: v1
kind: Pod
metadata:
  name: longhorn-test-pod
  namespace: default
spec:
  containers:
  - name: volume-test
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "while true; do echo $(date) >> /data/test.log; sleep 5; done"]
    volumeMounts:
    - name: longhorn-test-volume
      mountPath: /data
  volumes:
  - name: longhorn-test-volume
    persistentVolumeClaim:
      claimName: longhorn-test-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-test-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
