apiVersion: v1
kind: Service
metadata:
  name: szk-nginx-service
  namespace: ogloszenia-krytyczne
spec:
  type: NodePort  # Makes the service accessible from outside the cluster
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Expose on a specific port (30000-32767 range)
    protocol: TCP
    name: http
  selector:
    app: szk-nginx
